log4j added
DmGrt/Hibernate-cinema pull request #6
Opened 2020-10-15 10:13 UTC by DmGrt

2020-10-15 10:24 UTC, margarita-ignatieva commented on pom.xml
>          <plugins>
You also should add logs to .gitignore: logs/*

2020-10-15 10:24 UTC, margarita-ignatieva approved these changes

2020-10-15 19:59 UTC, KseniiaMakarova requested changes
**It will be great to have logging in DaoImpl classes as well**

2020-10-15 19:59 UTC, KseniiaMakarova commented on src/main/resources/log4j.properties
> +log4j.logger.org.hibernate.type.descriptor.sql=INFO
are hibernate logs also recorded? do you want to do this?

2020-10-15 19:59 UTC, KseniiaMakarova commented on src/main/java/com/dmgrt/cinema/Main.java
> +    private static final Logger logger = Logger.getRootLogger();
```suggestion
    private static final Logger logger = Logger.getLogger(Main.class);
```

2020-10-15 19:59 UTC, KseniiaMakarova commented on src/main/java/com/dmgrt/cinema/Main.java
> +        logger.info(movieSessionService.findAvailableSessions(3L, LocalDate.now()));
not all souts in this file are moved to logs - please fix this

2020-10-15 19:59 UTC, KseniiaMakarova commented on src/main/java/com/dmgrt/cinema/Main.java
>          jake = authenticationService.login("jake1956@meta.ua", "tort");
let's wrap this in try-catch and add log.warn with the informative message in `catch` block

2020-10-16 08:22 UTC, KseniiaMakarova requested changes
### **_please be attentive - not all comments from the previous review are fixed(_**

2020-10-16 08:22 UTC, KseniiaMakarova commented on src/main/java/com/dmgrt/cinema/Main.java
> +        System.out.println(movieSessionService.findAvailableSessions(2L, LocalDate.now()));
there are still souts above(

2020-10-16 08:22 UTC, KseniiaMakarova commented on src/main/java/com/dmgrt/cinema/Main.java
> +            logger.info("Can't register user." + e);
can your `register()` method throw Exception?

2020-10-16 12:43 UTC, KseniiaMakarova commented
![image](https://user-images.githubusercontent.com/59459757/96259487-593c5700-0fc6-11eb-9430-567b694633e4.png)

2020-10-16 13:18 UTC, DmGrt commented
🤦‍♂️ I'm so sorry, I don't know what happened to me today

2020-10-16 13:53 UTC, KseniiaMakarova approved these changes

2020-10-16 13:59 UTC, merged